#!/bin/bash

DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
replace_last_line='\r\033[K'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

# Check whether shell is interactive (otherwise we are running in a non-interactive script environment)
is_tty()
{
	[[ "$(/usr/bin/tty||true)" != "not a tty" ]]
}

is_windows()
{
	local res=$(uname | grep 'CYGWIN_NT')
	if [[ "$res" != "" ]]; then
		return 0
	else
		return 1
	fi
}

show_one_time_login()
{
	cd $DOCROOT_PATH
  echo -en "${yellow} Generating one-time-login link... ${NC} "
  one_time_login="$(fin drush uli)"
  echo -en "${replace_last_line}${green_bg} One-time-login link:${NC} "
  echo "$one_time_login"
}

# Yes/no confirmation dialog with an optional message
# @param $1 confirmation message
_confirm()
{
	# Skip checks if not a tty
	if ! is_tty; then
		return 0;
	fi

	while true; do
		read -p "$1 [y/n]: " answer
		case $answer in
			[Yy] | [Yy][Ee][Ss])
				break
			;;
			[Nn] | [Nn][Oo])
				exit 1
			;;
			*)
				echo 'Please answer yes or no.'
		esac
	done
}
#-------------------------- Execution --------------------------------

# Set repo root as working directory.
PROJECT_ROOT=$(git rev-parse --show-toplevel)
if [[ -z "$PROJECT_ROOT" ]]; then
	echo-red "Git repository was not found"
	exit 1;
fi

echo -e "${green_bg} Step 1 ${NC}${green} Creating services...${NC}"
fin up

echo "Waiting 10s for MySQL to initialize...";
sleep 10

if is_windows; then
	echo-green "Add ${VIRTUAL_HOST} to your hosts file (/etc/hosts), e.g.:"
	echo-green "192.168.64.100  ${VIRTUAL_HOST}"
	echo
fi
fin exec composer install
fin exec /var/www/vendor/bin/blt setup
echo -en "${green_bg} DONE! ${NC}"
echo -e " Open ${yellow}http://${VIRTUAL_HOST}${NC} in your browser to verify the setup."
show_one_time_login
